import type { CSSProperties } from "react";

/** Seven columns: agent, runs, avg cost, avg duration, accept, last run, view. */
const GRID = "1fr 90px 110px 110px 150px 130px 70px";

export const s = {
  page: { padding: "28px 28px 48px", maxWidth: 1180, margin: "0 auto" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 22,
  } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", margin: "6px 0 0" } satisfies CSSProperties,

  periodBar: { display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" } satisfies CSSProperties,
  periodBtn: (on: boolean): CSSProperties => ({
    border: `1px solid ${on ? "var(--accent)" : "var(--border)"}`,
    color: on ? "var(--accent)" : "var(--text-secondary)",
    background: on ? "color-mix(in srgb, var(--accent) 10%, transparent)" : "transparent",
    borderRadius: 7,
    padding: "6px 11px",
    fontSize: 12.5,
    cursor: "pointer",
  }),
  dateInput: {
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    borderRadius: 7,
    padding: "5px 9px",
    fontSize: 12.5,
  } satisfies CSSProperties,
  periodNote: { fontSize: 11.5, color: "var(--text-tertiary)", margin: "8px 0 0" } satisfies CSSProperties,

  cards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))",
    gap: 12,
    marginBottom: 20,
  } satisfies CSSProperties,
  statCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "16px 18px",
    minHeight: 104,
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 10.5,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: "var(--text-tertiary)",
    margin: 0,
  } satisfies CSSProperties,
  statValue: { fontSize: 30, fontWeight: 700, margin: "10px 0 0", lineHeight: 1.05 } satisfies CSSProperties,
  statUnit: { fontSize: 15, fontWeight: 600, color: "var(--text-secondary)", marginLeft: 3 } satisfies CSSProperties,
  statSub: { fontSize: 11.5, color: "var(--text-tertiary)", margin: "8px 0 0" } satisfies CSSProperties,
  statUnknown: { fontSize: 22, fontWeight: 600, margin: "12px 0 0", color: "var(--text-tertiary)" } satisfies CSSProperties,

  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border)",
    fontSize: 11,
    letterSpacing: ".06em",
    textTransform: "uppercase",
    color: "var(--text-tertiary)",
  } satisfies CSSProperties,
  sortBtn: (on: boolean): CSSProperties => ({
    background: "none",
    border: 0,
    padding: 0,
    font: "inherit",
    letterSpacing: "inherit",
    textTransform: "inherit",
    color: on ? "var(--text-primary)" : "inherit",
    cursor: "pointer",
    textAlign: "left",
  }),
  row: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "13px 16px",
    borderBottom: "1px solid var(--border)",
    alignItems: "center",
    fontSize: 13.5,
  } satisfies CSSProperties,
  agentCell: { display: "flex", alignItems: "center", gap: 9, minWidth: 0 } satisfies CSSProperties,
  agentName: { fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  num: { fontVariantNumeric: "tabular-nums" } satisfies CSSProperties,
  muted: { color: "var(--text-tertiary)" } satisfies CSSProperties,
  acceptCell: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  acceptPct: (good: boolean): CSSProperties => ({
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    color: good ? "var(--success)" : "var(--warning)",
  }),
  trend: (up: boolean): CSSProperties => ({
    fontSize: 12,
    color: up ? "var(--ok)" : "var(--crit)",
  }),
  denom: { fontSize: 11.5, color: "var(--text-tertiary)", fontVariantNumeric: "tabular-nums" } satisfies CSSProperties,
  viewBtn: {
    background: "none",
    border: 0,
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
    textAlign: "right",
  } satisfies CSSProperties,

  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "26px 0 12px",
    fontSize: 11,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: "var(--text-tertiary)",
  } satisfies CSSProperties,
  breakdown: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 12 } satisfies CSSProperties,
  slice: { display: "flex", alignItems: "center", gap: 10, padding: "7px 0", fontSize: 13 } satisfies CSSProperties,
  sliceBar: (pct: number, color: string): CSSProperties => ({
    height: 8,
    borderRadius: 4,
    background: color,
    width: `${Math.max(pct, 1)}%`,
    minWidth: 4,
    flex: "0 0 auto",
  }),
  sliceTrack: { flex: 1, height: 8, borderRadius: 4, background: "var(--bg-subtle)", overflow: "hidden" } satisfies CSSProperties,
  sliceCost: { fontVariantNumeric: "tabular-nums", fontWeight: 600, minWidth: 66, textAlign: "right" } satisfies CSSProperties,
  donutRow: { display: "flex", alignItems: "center", gap: 18, flexWrap: "wrap" } satisfies CSSProperties,
  legend: { flex: 1, minWidth: 170, display: "flex", flexDirection: "column", gap: 5 } satisfies CSSProperties,
  legendRow: { display: "flex", alignItems: "center", gap: 9, fontSize: 13 } satisfies CSSProperties,
  legendDot: (color: string): CSSProperties => ({
    width: 9,
    height: 9,
    borderRadius: 2,
    background: color,
    flex: "0 0 auto",
  }),
  legendLabel: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footnote: { fontSize: 11.5, color: "var(--text-tertiary)", margin: "14px 0 0", lineHeight: 1.5 } satisfies CSSProperties,
};
