import type { CSSProperties } from "react";

/** Co-located styles for SkillsTab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 220 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (on: boolean, dimmed: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: on ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.45 : dimmed ? 0.55 : on ? 1 : 0.8,
  }),
  handle: (draggable: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: draggable ? "grab" : "not-allowed",
    display: "flex",
    background: "transparent",
    border: "none",
    padding: 0,
  }),
  check: (on: boolean, locked: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    flexShrink: 0,
    borderRadius: 4,
    border: "1.5px solid " + (on ? "var(--accent)" : "var(--border-strong)"),
    background: on ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
    padding: 0,
    cursor: locked ? "not-allowed" : "pointer",
  }),
  name: { fontSize: 12.5, fontWeight: 600, flex: 1, minWidth: 0 } satisfies CSSProperties,
  typeBadge: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "1px 7px",
    borderRadius: 4,
  }),
  disabledTag: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    padding: "1px 7px",
    borderRadius: 4,
  } satisfies CSSProperties,
  savingNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  skeletonRow: { height: 40, borderRadius: 7 } satisfies CSSProperties,
} as const;
