import type { CSSProperties } from "react";

/** Co-located styles for DocList. */
export const s = {
  toolbar: {
    display: "flex",
    gap: 8,
    padding: 12,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  search: {
    flex: 1,
    minWidth: 0,
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  scroll: {
    maxHeight: 560,
    overflowY: "auto",
  } satisfies CSSProperties,
  groupHeader: {
    padding: "8px 12px 4px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  row: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 12px",
    border: "none",
    background: active ? "var(--bg-hover)" : "transparent",
    borderLeft: "2px solid " + (active ? "var(--accent)" : "transparent"),
    cursor: "pointer",
    textAlign: "left",
  }),
  rowPath: (dim: boolean): CSSProperties => ({
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: dim ? "var(--text-muted)" : "var(--text-primary)",
    textDecoration: dim ? "line-through" : "none",
  }),
  rowTokens: {
    fontSize: 11,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    padding: "10px 12px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  truncated: {
    padding: "8px 12px",
    fontSize: 12,
    color: "var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
} as const;
