/**
 * File-role classification: path → `SmartDiffRole`.
 *
 * Lives in `_shared` rather than in `smart-diff/` because a second consumer
 * needs it (`modules/brief/`, specs/10-pr-brief.md R2) and `no-cross-module-
 * internals` forbids importing another module's `helpers.ts` or `constants.ts`
 * directly. `pr_files` carries no `role` column — a file's role is always
 * *derived* from its path, never selected from the database
 * (`server/src/db/schema/pulls.ts`, `pr_files` has no such column) — so the
 * pattern table and the one classification rule move here, and
 * `modules/smart-diff/{helpers,constants}.ts` re-export them unchanged so its
 * own tests and call sites see no behaviour change.
 *
 * Patterns are matched against the POSIX path exactly as GitHub reports it on
 * `PrFile.path` (forward slashes, repo-relative, no leading `./`).
 */

import type { SmartDiffRole } from '@devdigest/shared';

/**
 * Role precedence. The classifier walks roles in THIS order and takes the first
 * whose pattern set matches, so a file that looks like two things resolves the
 * same way every time.
 *
 * Boilerplate wins over wiring because a lock file is also, technically, a
 * config file — and the acceptance criterion is that a lock file is ALWAYS
 * boilerplate, never merely usually.
 */
export const ROLE_ORDER: readonly SmartDiffRole[] = ['boilerplate', 'wiring', 'core'] as const;

/**
 * Boilerplate — generated or mechanical. Nobody reviews these line by line, and
 * a 4000-line lock diff at the top of the page buries the two lines that matter.
 *
 * Lock files are listed by exact basename rather than by a `*.lock` glob: the
 * set is small, closed, and known, and a glob would also swallow hand-written
 * files that happen to end in `.lock`.
 */
export const BOILERPLATE_PATTERNS: readonly RegExp[] = [
  // Dependency lock files + the manifests they are generated from.
  /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/,
  /(^|\/)(Cargo\.lock|poetry\.lock|Pipfile\.lock|Gemfile\.lock|composer\.lock|go\.sum|uv\.lock)$/,
  /(^|\/)(package\.json|composer\.json|Gemfile|go\.mod|requirements\.txt)$/,
  // Build output and vendored trees — checked in, never authored.
  /(^|\/)(dist|build|out|coverage|node_modules|vendor|\.next|target)\//,
  // Test snapshots: regenerated by the test run, not written by hand.
  /(^|\/)__snapshots__\//,
  /\.snap$/,
  // Generated sources, by the two conventions that actually appear in the wild.
  /\.(generated|gen)\.[a-z]+$/,
  /(^|\/)(migrations|__generated__)\//,
  // Minified / sourcemapped artefacts.
  /\.min\.(js|css)$/,
  /\.map$/,
  // Lockstep metadata: no logic can hide in these.
  /(^|\/)(CHANGELOG\.md|\.gitignore|LICENSE)$/,
] as const;

/**
 * Wiring — the change is real but it is plumbing: configuration, registration,
 * barrels, entrypoints. Worth reading, not worth reading first.
 *
 * Barrel files (`index.*`) are wiring only when they are barrels. An
 * `index.ts` that IS the module (a route handler named `index.ts`) still lands
 * here — accepted: the cost of misfiling a barrel is one extra group down, and
 * distinguishing them needs the file body, which would make the classifier
 * non-deterministic on a patch-less file.
 */
export const WIRING_PATTERNS: readonly RegExp[] = [
  // Barrels and entrypoints.
  /(^|\/)index\.(ts|tsx|js|jsx|mjs|cjs)$/,
  /(^|\/)(main|server|app|bootstrap|entrypoint)\.(ts|tsx|js|jsx|py|go|rs)$/,
  // Configuration, by name and by the `*.config.*` convention.
  /(^|\/)[\w.-]*\.config\.(ts|js|mjs|cjs|json|yaml|yml)$/,
  /(^|\/)(tsconfig|jsconfig)([.\w-]*)?\.json$/,
  /(^|\/)config\.(ts|tsx|js|json|yaml|yml|toml)$/,
  /(^|\/)(config|configs|settings)\//,
  // Env, containers, CI, infra.
  /(^|\/)\.env($|\.)/,
  /(^|\/)(Dockerfile|docker-compose[\w.-]*\.ya?ml|Procfile|Makefile)$/,
  /(^|\/)\.github\//,
  /(^|\/)(\.circleci|\.gitlab-ci\.yml|terraform|helm|k8s)\//,
  // Dotfiles at any level: lint, format, editor, hooks.
  /(^|\/)\.[\w-]+rc(\.[\w]+)?$/,
  /(^|\/)(eslint|prettier|vitest|jest|tailwind|next|vite|rollup|webpack)\.[\w.]*$/,
] as const;

const PATTERNS: Record<SmartDiffRole, readonly RegExp[]> = {
  boilerplate: BOILERPLATE_PATTERNS,
  wiring: WIRING_PATTERNS,
  // core is the fallthrough: it has no patterns of its own, on purpose. A rule
  // list for "business logic" would be a list of every language's file
  // extensions, and it would be wrong for the next repo.
  core: [],
};

/** Normalise a repo-relative path so the patterns only ever see POSIX form. */
export function normalizePath(path: string): string {
  return path.replace(/\\/g, '/').replace(/^\.\//, '');
}

/**
 * The single classification rule. First matching role in `ROLE_ORDER` wins, so
 * `package-lock.json` is boilerplate even though it is also configuration.
 */
export function classifyPath(path: string): SmartDiffRole {
  const p = normalizePath(path);
  for (const role of ROLE_ORDER) {
    if (PATTERNS[role].some((re) => re.test(p))) return role;
  }
  return 'core';
}
