#!/usr/bin/env bash
# Deterministic dependency facts for the dependency-checker skill.
#
# Emits markdown to stdout. Every number in the report must come from here —
# nothing about install size or version drift is guessable, and a plausible
# wrong number is worse than no number.
#
#   "$CLAUDE_PLUGIN_ROOT"/skills/dependency-checker/scripts/survey.sh [--top N]
#
# Reads only. Needs python3 and du; no npm/pnpm install and no network.
set -euo pipefail

TOP="${2:-12}"
# The project being surveyed is the one the session is working in — NOT the
# directory this script lives in. Walking up from $0 finds the repository only
# when the skill is run from a checkout; once installed as a plugin the same
# walk lands inside the plugin cache and the survey measures itself.
root="${CLAUDE_PROJECT_DIR:-$PWD}"
cd "$root"

# server/clones/ is a full copy of this repository, including its node_modules.
# Every scan must exclude it or every number doubles.
PKGS=(server client reviewer-core e2e mcp evals)

echo "# Dependency survey — $(basename "$root")"
echo
echo "Generated by \`scripts/survey.sh\`. Excludes \`server/clones/**\`."
echo

echo "## 1. Packages"
echo
printf '| package | manager | lockfile | prod deps | dev deps | node_modules |\n'
printf '| --- | --- | --- | --- | --- | --- |\n'
for p in "${PKGS[@]}"; do
  [ -f "$p/package.json" ] || continue
  if [ -f "$p/pnpm-lock.yaml" ]; then mgr=pnpm; lock=pnpm-lock.yaml
  elif [ -f "$p/package-lock.json" ]; then mgr=npm; lock=package-lock.json
  else mgr='?'; lock='**none**'; fi
  counts=$(python3 -c "
import json;d=json.load(open('$p/package.json'))
print(len(d.get('dependencies') or {}), len(d.get('devDependencies') or {}))")
  size=$(du -sh "$p/node_modules" 2>/dev/null | cut -f1 || echo 'not installed')
  printf '| `%s` | %s | `%s` | %s | %s | %s |\n' "$p" "$mgr" "$lock" ${counts} "$size"
done
echo

echo "## 2. Declared in more than one package"
echo
python3 - "${PKGS[@]}" <<'PY'
import json, sys, collections
pkgs = sys.argv[1:]
seen = collections.defaultdict(dict)
for p in pkgs:
    try: d = json.load(open(f'{p}/package.json'))
    except FileNotFoundError: continue
    for kind in ('dependencies', 'devDependencies'):
        for name, rng in (d.get(kind) or {}).items():
            seen[name][p] = (rng, kind == 'devDependencies')
multi = {k: v for k, v in seen.items() if len(v) > 1}
drift = {k: v for k, v in multi.items() if len({r for r, _ in v.values()}) > 1}
print(f'{len(seen)} distinct direct dependencies; {len(multi)} declared in more than one package; '
      f'**{len(drift)} with a different range**.\n')
print('| dependency | packages | ranges | drift |')
print('| --- | --- | --- | --- |')
for k in sorted(multi):
    where = ', '.join(f'`{p}`' + ('*' if dev else '') for p, (_, dev) in sorted(multi[k].items()))
    ranges = ' · '.join(sorted({r for r, _ in multi[k].values()}))
    print(f'| `{k}` | {where} | `{ranges}` | {"**YES**" if k in drift else "—"} |')
print('\n`*` = devDependency.')
PY
echo

echo "## 3. Installed version drift (what is actually on disk)"
echo
python3 - "${PKGS[@]}" <<'PY'
import json, os, sys, collections
pkgs = sys.argv[1:]
inst = collections.defaultdict(dict)
for p in pkgs:
    nm = f'{p}/node_modules'
    if not os.path.isdir(nm): continue
    try: names = list((json.load(open(f'{p}/package.json')).get('dependencies') or {}) |
                      (json.load(open(f'{p}/package.json')).get('devDependencies') or {}))
    except FileNotFoundError: continue
    for name in names:
        try: inst[name][p] = json.load(open(f'{nm}/{name}/package.json'))['version']
        except Exception: pass
rows = {k: v for k, v in inst.items() if len(v) > 1 and len(set(v.values())) > 1}
if not rows:
    print('No direct dependency is installed at two different versions.')
else:
    print('A dependency installed at two versions is only a problem when one package '
          'consumes another\'s SOURCE through a tsconfig path alias — then one tsc program '
          'sees both. Check the alias graph in section 5 before acting.\n')
    print('| dependency | installed |')
    print('| --- | --- |')
    for k in sorted(rows):
        print(f'| `{k}` | ' + ' · '.join(f'`{p}` {v}' for p, v in sorted(rows[k].items())) + ' |')
PY
echo

echo "## 4. Heaviest installed packages"
echo
for p in "${PKGS[@]}"; do
  [ -d "$p/node_modules" ] || continue
  echo "### \`$p\` — top $TOP on disk"
  echo '```'
  # Both globs are needed for scoped packages, and the first one also matches the
  # bare scope directory (`@next/`) — drop those rows or every scope is counted twice.
  du -sk "$p"/node_modules/*/ "$p"/node_modules/@*/*/ 2>/dev/null \
    | grep -vE 'node_modules/@[^/]+/$' \
    | sort -rn | head -"$TOP" \
    | awk '{printf "%8.1f MB  %s\n", $1/1024, $2}' \
    | sed "s#$p/node_modules/##"
  echo '```'
  echo
done

echo "## 5. Cross-package edges (tsconfig path aliases, not npm)"
echo
echo 'These packages are not published to each other; they are wired by path alias'
echo 'and consumed as TypeScript source. An alias means one tsc program pulls the'
echo "other package's files in — and resolves their bare imports against THAT"
echo "package's node_modules."
echo
printf '| from | alias | to |\n| --- | --- | --- |\n'
for p in "${PKGS[@]}"; do
  [ -f "$p/tsconfig.json" ] || continue
  python3 - "$p" <<'PY'
import json, re, sys
p = sys.argv[1]
raw = open(f'{p}/tsconfig.json').read()
raw = re.sub(r'^\s*//.*$', '', raw, flags=re.M)
paths = (json.loads(raw).get('compilerOptions') or {}).get('paths') or {}
for alias, targets in paths.items():
    if alias.endswith('/*'): continue
    print(f'| `{p}` | `{alias}` | `{targets[0]}` |')
PY
done
