import type { CSSProperties } from "react";

/** Co-located styles for the export wizard's four steps. Measurements copied
 *  from `design-mocks/src/20-screen_export.jsx` per
 *  `specs/15-export-to-ci.md` → "Design conformance". */
export const s = {
  stepBody: { padding: 20 } satisfies CSSProperties,
  stepBar: { padding: "18px 20px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", width: "100%" } satisfies CSSProperties,
  footerRight: { marginLeft: "auto" } satisfies CSSProperties,

  // Target step
  targetGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 } satisfies CSSProperties,
  targetCard: (selected: boolean, disabled: boolean): CSSProperties => ({
    textAlign: "left",
    padding: 16,
    borderRadius: 10,
    cursor: disabled ? "not-allowed" : "pointer",
    background: "var(--bg-surface)",
    border: `1.5px solid ${selected ? "var(--accent)" : "var(--border)"}`,
    opacity: disabled ? 0.55 : 1,
    width: "100%",
  }),
  targetCardHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  targetIconTile: (selected: boolean): CSSProperties => ({
    width: 34,
    height: 34,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    display: "grid",
    placeItems: "center",
    color: selected ? "var(--accent)" : "var(--text-secondary)",
    flexShrink: 0,
  }),
  targetName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  targetDesc: { fontSize: 12, color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
  repoField: { marginTop: 20 } satisfies CSSProperties,

  // Preview step
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
  } satisfies CSSProperties,
  previewFilesPane: {
    borderRight: "1px solid var(--border)",
    padding: 10,
    background: "var(--bg-surface)",
    overflow: "auto",
  } satisfies CSSProperties,
  previewFilesLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    padding: "2px 8px 8px",
  } satisfies CSSProperties,
  previewFileRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 8px",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 12,
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
  }),
  previewContentPane: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  previewContentHeader: {
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  previewContentPath: { fontSize: 12, flex: 1 } satisfies CSSProperties,
  previewPre: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    overflow: "auto",
    flex: 1,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  previewCenter: { display: "grid", placeItems: "center", height: 340 } satisfies CSSProperties,

  // Configure step
  configureWrap: { maxWidth: 600, display: "grid", gap: 4 } satisfies CSSProperties,
  chipsRow: { display: "flex", flexWrap: "wrap", gap: 7 } satisfies CSSProperties,
  postAsList: { display: "flex", flexDirection: "column", gap: 7 } satisfies CSSProperties,
  postAsLabel: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  radioOuter: (selected: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 99,
    border: `1.5px solid ${selected ? "var(--accent)" : "var(--border-strong)"}`,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  radioInner: { width: 8, height: 8, borderRadius: 99, background: "var(--accent)" } satisfies CSSProperties,
  secretsBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
  } satisfies CSSProperties,
  secretRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  secretKey: { width: 160, flexShrink: 0, fontSize: 12.5 } satisfies CSSProperties,
  secretDesc: { flex: 1, fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  infoBox: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "11px 13px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginTop: 14,
  } satisfies CSSProperties,
  infoBoxIcon: { color: "var(--text-muted)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  infoBoxText: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,

  // Install step
  installWrap: { maxWidth: 600 } satisfies CSSProperties,
  installCard: {
    width: "100%",
    textAlign: "left",
    padding: 18,
    borderRadius: 10,
    border: "1.5px solid var(--accent)",
    background: "var(--accent-bg)",
  } satisfies CSSProperties,
  installCardHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  installCardBody: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  installHelp: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 14,
    textAlign: "center",
  } satisfies CSSProperties,
  installDoneBox: { textAlign: "center", padding: "24px 12px", display: "grid", gap: 12 } satisfies CSSProperties,
} as const;
