/**
 * Constants for the smart-diff module — every threshold and every path pattern
 * that decides a file's role lives here, and nowhere else.
 *
 * The classifier is deliberately data-driven: tuning it is editing this file,
 * not editing control flow. Patterns are matched against the POSIX path exactly
 * as GitHub reports it on `PrFile.path` (forward slashes, repo-relative, no
 * leading `./`).
 */

import type { SmartDiffRole } from '@devdigest/shared';

/**
 * Role precedence. The classifier walks roles in THIS order and takes the first
 * whose pattern set matches, so a file that looks like two things resolves the
 * same way every time.
 *
 * Boilerplate wins over wiring because a lock file is also, technically, a
 * config file — and the acceptance criterion is that a lock file is ALWAYS
 * boilerplate, never merely usually.
 */
export const ROLE_ORDER: readonly SmartDiffRole[] = ['boilerplate', 'wiring', 'core'] as const;

/** Display order of the groups in the response — highest risk first. */
export const GROUP_ORDER: readonly SmartDiffRole[] = ['core', 'wiring', 'boilerplate'] as const;

/**
 * Boilerplate — generated or mechanical. Nobody reviews these line by line, and
 * a 4000-line lock diff at the top of the page buries the two lines that matter.
 *
 * Lock files are listed by exact basename rather than by a `*.lock` glob: the
 * set is small, closed, and known, and a glob would also swallow hand-written
 * files that happen to end in `.lock`.
 */
export const BOILERPLATE_PATTERNS: readonly RegExp[] = [
  // Dependency lock files + the manifests they are generated from.
  /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/,
  /(^|\/)(Cargo\.lock|poetry\.lock|Pipfile\.lock|Gemfile\.lock|composer\.lock|go\.sum|uv\.lock)$/,
  /(^|\/)(package\.json|composer\.json|Gemfile|go\.mod|requirements\.txt)$/,
  // Build output and vendored trees — checked in, never authored.
  /(^|\/)(dist|build|out|coverage|node_modules|vendor|\.next|target)\//,
  // Test snapshots: regenerated by the test run, not written by hand.
  /(^|\/)__snapshots__\//,
  /\.snap$/,
  // Generated sources, by the two conventions that actually appear in the wild.
  /\.(generated|gen)\.[a-z]+$/,
  /(^|\/)(migrations|__generated__)\//,
  // Minified / sourcemapped artefacts.
  /\.min\.(js|css)$/,
  /\.map$/,
  // Lockstep metadata: no logic can hide in these.
  /(^|\/)(CHANGELOG\.md|\.gitignore|LICENSE)$/,
] as const;

/**
 * Wiring — the change is real but it is plumbing: configuration, registration,
 * barrels, entrypoints. Worth reading, not worth reading first.
 *
 * Barrel files (`index.*`) are wiring only when they are barrels. An
 * `index.ts` that IS the module (a route handler named `index.ts`) still lands
 * here — accepted: the cost of misfiling a barrel is one extra group down, and
 * distinguishing them needs the file body, which would make the classifier
 * non-deterministic on a patch-less file.
 */
export const WIRING_PATTERNS: readonly RegExp[] = [
  // Barrels and entrypoints.
  /(^|\/)index\.(ts|tsx|js|jsx|mjs|cjs)$/,
  /(^|\/)(main|server|app|bootstrap|entrypoint)\.(ts|tsx|js|jsx|py|go|rs)$/,
  // Configuration, by name and by the `*.config.*` convention.
  /(^|\/)[\w.-]*\.config\.(ts|js|mjs|cjs|json|yaml|yml)$/,
  /(^|\/)(tsconfig|jsconfig)([.\w-]*)?\.json$/,
  /(^|\/)config\.(ts|tsx|js|json|yaml|yml|toml)$/,
  /(^|\/)(config|configs|settings)\//,
  // Env, containers, CI, infra.
  /(^|\/)\.env($|\.)/,
  /(^|\/)(Dockerfile|docker-compose[\w.-]*\.ya?ml|Procfile|Makefile)$/,
  /(^|\/)\.github\//,
  /(^|\/)(\.circleci|\.gitlab-ci\.yml|terraform|helm|k8s)\//,
  // Dotfiles at any level: lint, format, editor, hooks.
  /(^|\/)\.[\w-]+rc(\.[\w]+)?$/,
  /(^|\/)(eslint|prettier|vitest|jest|tailwind|next|vite|rollup|webpack)\.[\w.]*$/,
] as const;

/**
 * A PR at or above EITHER threshold is flagged `too_big` and offered a split.
 *
 * 400 changed lines is where review quality is measured to fall off a cliff
 * (SmartBear/Cisco: defect-detection collapses past ~400 LOC in one sitting);
 * 20 files is the point where the reviewer stops holding the whole change in
 * their head. Boilerplate is excluded from both counts — a lock file does not
 * make a PR hard to review, and counting it would flag every dependency bump.
 */
export const SPLIT_MAX_REVIEWABLE_LINES = 400;
export const SPLIT_MAX_REVIEWABLE_FILES = 20;

/**
 * A proposed split must have at least this many files. A one-file "split" is
 * not a split, it is a file — suggesting it is noise.
 */
export const SPLIT_MIN_FILES_PER_GROUP = 2;

/**
 * How many path segments name a proposed split (`src/modules/pulls` at 3).
 * Two would put all of `src/*` in one bucket; four splits siblings that
 * genuinely belong together.
 */
export const SPLIT_GROUP_DEPTH = 3;

/** Never propose more than this many splits — past it the advice is not advice. */
export const SPLIT_MAX_GROUPS = 5;
